// Placeholder for V2015 Schemas
export const itchV2015Schemas = {
  'T': { name: 'Time Stamp Seconds', fields: [{ name: 'second', type: 'uint32' }] },
  'S': { name: 'System Event', fields: [{ name: 'eventCode', type: 'alpha', length: 1 }] },
  'R': { name: 'Orderbook Directory', fields: [{ name: 'orderBookId', type: 'uint32' }, { name: 'symbol', type: 'alpha', length: 16 }] },
  'L': { name: 'Price Tick Size', fields: [{ name: 'orderBookId', type: 'uint32' }, { name: 'tickSizeId', type: 'uint32' }] },
  'M': { name: 'Quantity Tick Size', fields: [{ name: 'orderBookId', type: 'uint32' }, { name: 'tickSizeId', type: 'uint32' }] },
  'A': { name: 'Add Order', fields: [{ name: 'orderReferenceNumber', type: 'uint64' }, { name: 'buySellIndicator', type: 'alpha', length: 1 }, { name: 'shares', type: 'uint32' }, { name: 'orderBookId', type: 'uint32' }, { name: 'price', type: 'uint32_price' }] },
  'E': { name: 'Order Executed', fields: [{ name: 'orderReferenceNumber', type: 'uint64' }, { name: 'executedShares', type: 'uint32' }, { name: 'matchNumber', type: 'uint64' }] },
  'C': { name: 'Order Executed With Price', fields: [{ name: 'orderReferenceNumber', type: 'uint64' }, { name: 'executedShares', type: 'uint32' }, { name: 'matchNumber', type: 'uint64' }, { name: 'printable', type: 'alpha', length: 1 }, { name: 'executionPrice', type: 'uint32_price' }] },
  'B': { name: 'Broken Trade', fields: [{ name: 'matchNumber', type: 'uint64' }] },
  'D': { name: 'Order Delete', fields: [{ name: 'orderReferenceNumber', type: 'uint64' }] },
  'U': { name: 'Order Replace', fields: [{ name: 'originalOrderReferenceNumber', type: 'uint64' }, { name: 'newOrderReferenceNumber', type: 'uint64' }, { name: 'shares', type: 'uint32' }, { name: 'price', type: 'uint32_price' }] },
  'P': { name: 'Trade', fields: [{ name: 'orderReferenceNumber', type: 'uint64' }, { name: 'buySellIndicator', type: 'alpha', length: 1 }, { name: 'shares', type: 'uint32' }, { name: 'orderBookId', type: 'uint32' }, { name: 'price', type: 'uint32_price' }, { name: 'matchNumber', type: 'uint64' }] },
  'O': { name: 'BBO Quotation', fields: [{ name: 'orderBookId', type: 'uint32' }, { name: 'bestBidPrice', type: 'uint32_price' }, { name: 'bestBidSize', type: 'uint32' }, { name: 'bestAskPrice', type: 'uint32_price' }, { name: 'bestAskSize', type: 'uint32' }] },
  'N': { name: 'News Item', fields: [{ name: 'newsId', type: 'uint32' }, { name: 'headline', type: 'alpha', length: 100 }] },
  'f': { name: 'Foreign Shares Available', fields: [{ name: 'orderBookId', type: 'uint32' }, { name: 'sharesAvailable', type: 'uint32' }, { name: 'foreignBoard', type: 'alpha', length: 1 }] },
  'e': { name: 'Order Executed with Broker ID', fields: [{ name: 'orderReferenceNumber', type: 'uint64' }, { name: 'executedShares', type: 'uint32' }, { name: 'matchNumber', type: 'uint64' }, { name: 'brokerId', type: 'alpha', length: 4 }] },
  'c': { name: 'Order Executed With Price and Broker ID', fields: [{ name: 'orderReferenceNumber', type: 'uint64' }, { name: 'executedShares', type: 'uint32' }, { name: 'matchNumber', type: 'uint64' }, { name: 'printable', type: 'alpha', length: 1 }, { name: 'executionPrice', type: 'uint32_price' }, { name: 'brokerId', type: 'alpha', length: 4 }] },
  'p': { name: 'Trade with Broker ID', fields: [{ name: 'orderReferenceNumber', type: 'uint64' }, { name: 'buySellIndicator', type: 'alpha', length: 1 }, { name: 'shares', type: 'uint32' }, { name: 'orderBookId', type: 'uint32' }, { name: 'price', type: 'uint32_price' }, { name: 'matchNumber', type: 'uint64' }, { name: 'brokerId', type: 'alpha', length: 4 }] },
  's': { name: 'Trading Schedule', fields: [{ name: 'orderBookId', type: 'uint32' }, { name: 'scheduleCode', type: 'alpha', length: 1 }] },
  'k': { name: 'Orderbook Restrictions', fields: [{ name: 'orderBookId', type: 'uint32' }, { name: 'restrictionCode', type: 'alpha', length: 1 }] },
  'Y': { name: 'Index Member Directory', fields: [{ name: 'indexId', type: 'uint32' }, { name: 'orderBookId', type: 'uint32' }] },
  'Z': { name: 'Index Value', fields: [{ name: 'indexId', type: 'uint32' }, { name: 'value', type: 'uint64' }] },
  'H': { name: 'Orderbook Trading Action', fields: [{ name: 'orderBookId', type: 'uint32' }, { name: 'tradingState', type: 'alpha', length: 1 }] },
  'I': { name: 'Indicative Price/Quantity', fields: [{ name: 'orderBookId', type: 'uint32' }, { name: 'bidVolume', type: 'uint32' }, { name: 'askVolume', type: 'uint32' }, { name: 'bestBidPrice', type: 'uint32_price' }, { name: 'bestAskPrice', type: 'uint32_price' }, { name: 'equilibriumPrice', type: 'uint32_price' }] }
};
